import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <>
          <nav className='flex justify-between min-h-[10vh] px-10 items-center'>
            <ul className='flex'>
              <li className='mr-5'>
                <Link href={'/'}>Home</Link>
              </li>
              <li className='underline underline-offset-4'>
                <Link href={'/chart'}>Chart</Link>
              </li>
            </ul>
            <ul className='flex'>
              <li className='mr-5'>
                <Link href={'/account/login'}>Log in</Link>
              </li>
              <li>
                <Link href={'/account/signup'}>Sign up</Link>
              </li>
            </ul>
          </nav>
          {children}
        </>
      </body>
    </html>
  );
}
